services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3001:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
      OPENAI_API_BASE_URL: "https://openrouter.ai/api/v1"
      OPENAI_API_KEY: ${OPENROUTER_API_KEY}
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
      WEBUI_URL: "https://ai.merakisystems.com"
      WEBUI_SESSION_COOKIE_SAME_SITE: "lax"
      WEBUI_SESSION_COOKIE_SECURE: "true"
      ENABLE_OAUTH_SIGNUP: "true"
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OPENID_PROVIDER_URL: "https://auth.merakisystems.com/application/o/open-web-ui/.well-known/openid-configuration"
      OAUTH_PROVIDER_NAME: "Authentik"
      OAUTH_SCOPES: "openid email profile"
    networks:
      - default
      - nginx_proxy_manager_default

networks:
  nginx_proxy_manager_default:
    external: true

volumes:
  open-webui:
