services:
  config-sync:
    image: alpine
    restart: no
    volumes:
      - nginx_custom:/config
    environment:
      GIT_REPO: ${GIT_REPO}
    command: sh -c "apk add --no-cache git -q && git clone --depth 1 $$GIT_REPO /tmp/repo && mkdir -p /config && cp /tmp/repo/nginx_proxy_manager/custom/http.conf /config/http.conf"

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    depends_on:
      config-sync:
        condition: service_completed_successfully
    ports:
      - "${NPM_BIND_IP}:80:80"
      - "${NPM_BIND_IP}:443:443"
      - "${NPM_BIND_IP}:81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - nginx_custom:/data/nginx/custom

volumes:
  nginx_custom:
