---

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "${HOMEPAGE_PORT:-3000}:3000"
    volumes:
      - homepage_logs:/app/config/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: services
        target: /app/config/services.yaml
      - source: settings
        target: /app/config/settings.yaml
      - source: widgets
        target: /app/config/widgets.yaml
      - source: docker_cfg
        target: /app/config/docker.yaml
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    networks:
      - default
      - nginx_proxy_manager_default

volumes:
  homepage_logs:

configs:
  services:
    file: ./config/services.yaml
  settings:
    file: ./config/settings.yaml
  widgets:
    file: ./config/widgets.yaml
  docker_cfg:
    file: ./config/docker.yaml

networks:
  nginx_proxy_manager_default:
    external: true
