# Download base image ubuntu 22.04
FROM ubuntu:22.04

# LABEL about the custom image
LABEL maintainer="admin@merakisystems.com"
LABEL version="0.1"
LABEL description="This is a custom Docker Image for NODERED running on Ubuntu."


# Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

# Update Ubuntu Software repository
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install software-properties-common git -y
RUN apt install nano curl iputils-ping -y


# install COCKPIT
RUN apt install cockpit -y
RUN sudo apt install cockpit -y
RUN sudo apt install cockpit-dashboard cockpit-storaged cockpit-networkmanager cockpit-selinux cockpit-docker cockpit-doc cockpit-kdump cockpit-kubernetes cockpit-machines cockpit-packagekit cockpit-pcp cockpit-sosreport cockpit-subscriptions cockpit-tests cockpit-ws -y

# Copy start.sh script and define default command for the container
# COPY start.sh /start.sh

RUN echo "tail -f /dev/null" > /start.sh
RUN chmod +x /start.sh

CMD ["./start.sh"]


# Expose Port for the Application 
EXPOSE 80 443