version: "3.9"

services:
  init-settings:
    image: curlimages/curl:8.2.1
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -eux
        # Download into a safe, writable temporary folder
        curl -fL --retry 3 \
          https://raw.githubusercontent.com/garethdesilva/merakisystems/ca0af9f3dc845f510a6414055ff8889a53ef3a2b/searxng/settings.yml \
          -o /tmp/settings.yml

        # Move the file into the volume
        mkdir -p /data
        mv /tmp/settings.yml /data/settings.yml

    volumes:
      - searxng_settings:/data

  searxng:
    image: searxng/searxng:latest
    depends_on:
      init-settings:
        condition: service_completed_successfully
    ports:
      - "8181:8080"
    volumes:
      - searxng_settings:/etc/searxng/
    environment:
      - BIND_ADDRESS=0.0.0.0:8080

volumes:
  searxng_settings:
