version: "3.9"

services:
  init-settings:
    image: alpine:3.18
    entrypoint: |
      sh -c "cat <<EOF > /data/settings.yml
search:
  formats:
    - html
    - json
EOF"
    volumes:
      - searxng_settings:/data

  searxng:
    image: searxng/searxng:latest
    depends_on:
      init-settings:
        condition: service_completed_successfully
    ports:
      - "8181:8080"
    volumes:
      - searxng_settings:/etc/searxng/
    environment:
      - BIND_ADDRESS=0.0.0.0:8080

volumes:
  searxng_settings:
