version: "3.9"

services:
  init-settings:
    image: curlimages/curl:8.2.1
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -eux
        curl -fsSL \
          https://github.com/garethdesilva/merakisystems/main/searxng/settings.yml \
          -o /data/settings.yml
    volumes:
      - searxng_settings:/data

  searxng:
    image: searxng/searxng:latest
    depends_on:
      init-settings:
        condition: service_completed_successfully
    ports:
      - "8181:8080"
    volumes:
      - searxng_settings:/etc/searxng/
    environment:
      - BIND_ADDRESS=0.0.0.0:8080

volumes:
  searxng_settings:
